config/routes.rb
Rails.application.routes.draw do
  resources :vehicles do
    collection { post :import }
  end

 root 'vehicles#index'

end

app/models/vehicle.rb
class Vehicle < ActiveRecord::Base
   
# video on pg_search -- couldn't get working w/o view
#  extend Textacular
#   attr_accessor :query
##   belongs_to :searchable
## 
#   def results 
#     if @query.present?
#       self.class.search(@query).preload(:searchable).map!(&:searchable).uniq
#     else
#       Search.none
#     end
#   end
     
# rails cast #37 -- explains adding search
#  def self.search(search)
#    if search
#       find(:all, :conditions => ['vehicle LIKE ?', "%#{search}%"])
#    else
#       find(:all)
#    end  
#  end
  
  def self.import(file)
    CSV.foreach(file.path, headers: true) do |row|
      Vehicle.create! row.to_hash
    end
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/vehicles_controller.rb
class VehiclesController < ApplicationController
  before_action :set_vehicle, only: [:show, :edit, :update, :destroy]
  
#  helper_method :sort_column, :sort_direction

  # GET /vehicles
  # GET /vehicles.json
# couldn't get this to work -- search
#  def index
#    if params[:search].present?
#       @vehicles = Vehicle.new(query: params[:search]).results
#    else 
#       @vehicles = Vehicle.order(sort_column + " " + sort_direction)
#    end
#  end  , :conditions => ['desc LIKE ?', "%#{params[:search]}%"])
  
  def index
   @search = Vehicle.search(params[:q])
   if :q
     @vehicles = @search.result
     @search.build_condition
   else
     @vehicles = Vehicle.all  
   end
  
#    if @search
#       @vechicles = @search.result
#    else
#      @vehicles = Vehicle.all
#    end

#     created a search dialog box -- replaced with ransack
#     if params[:search]
#        @vehicles = Vehicle.where(vehicle: params[:search])
#     else
#        @vehicles = Vehicle.all
#     end
  end

  # GET /vehicles/1
  # GET /vehicles/1.json
  def show
  end

  # GET /vehicles/new
  def new
    @vehicle = Vehicle.new
  end

  # GET /vehicles/1/edit
  def edit
  end

  # POST /vehicles
  # POST /vehicles.json
  def create
    @vehicle = Vehicle.new(vehicle_params)

    respond_to do |format|
      if @vehicle.save
        format.html { redirect_to @vehicle, notice: 'Vehicle was successfully created.' }
        format.json { render :show, status: :created, location: @vehicle }
      else
        format.html { render :new }
        format.json { render json: @vehicle.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /vehicles/1
  # PATCH/PUT /vehicles/1.json
  def update
    respond_to do |format|
      if @vehicle.update(vehicle_params)
        format.html { redirect_to @vehicle, notice: 'Vehicle was successfully updated.' }
        format.json { render :show, status: :ok, location: @vehicle }
      else
        format.html { render :edit }
        format.json { render json: @vehicle.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vehicles/1
  # DELETE /vehicles/1.json
  def destroy
    @vehicle.destroy
    respond_to do |format|
      format.html { redirect_to vehicles_url, notice: 'Vehicle was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  
  def import
    Vehicle.import(params[:file])
    redirect_to root_url , notice: "Vehicle records imported."
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_vehicle
      @vehicle = Vehicle.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def vehicle_params
       params.require(:vehicle).permit(:vehicle, :date, :desc, :mileage, :category, :cost)
#       params.permit(:vehicle, :date, :desc, :mileage, :category, :cost)
    end
    
#   learned how to add sort and direction links -- replaced with ransak gem
#    def sort_column
#      Vehicle.column_names.include?(params[:sort]) ? params[:sort] : "vehicle"
#    end
#    
#    def sort_direction
#      %w[asc desc].include?(params[:direction])? params[:direction] : "asc"
#    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  # rails cast #228 - explains sorting columns
  def sortable(column, title = nil)
    title ||= column.titleize
    direction = column == sort_column && sort_direction == "asc"? "desc" : "asc"
    link_to title, :sort => column, :direction => direction
    
  end
end

app/helpers/vehicles_helper.rb
module VehiclesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>StreetCars</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/vehicles/_form.html.erb
<%= form_for(@vehicle) do |f| %>
  <% if @vehicle.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@vehicle.errors.count, "error") %> prohibited this vehicle from being saved:</h2>

      <ul>
      <% @vehicle.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :vehicle %><br>
    <%= f.text_field :vehicle %>
  </div>
  <div class="field">
    <%= f.label :date %><br>
    <%= f.date_select :date %>
  </div>
  <div class="field">
    <%= f.label :desc %><br>
    <%= f.text_field :desc %>
  </div>
  <div class="field">
    <%= f.label :mileage %><br>
    <%= f.number_field :mileage %>
  </div>
  <div class="field">
    <%= f.label :category %><br>
    <%= f.text_field :category %>
  </div>
  <div class="field">
    <%= f.label :cost %><br>
    <%= f.text_field :cost %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/vehicles/edit.html.erb
<h1>Editing vehicle</h1>

<%= render 'form' %>

<%= link_to 'Show', @vehicle %> |
<%= link_to 'Back', vehicles_path %>

app/views/vehicles/index.html.erb
<h1>Listing vehicles</h1>
 <%= search_form_for @search do |f| %>
   <%= f.condition_fields do |c| %>
	  <div class="field">
	  	<%= c.attribute_fields do |a| %>
	  	  <%= a.attribute_select %>
	  	<% end %>
	  	<%= c.predicate_select %>
	  	<%= c.value_fields do |v| %>
	  	  <%= v.text_field :value %>
	  	<% end %>
	  </div>
   <% end %>
	  <div class="actions">
	  	<%= f.submit "Search" %>
	  </div>
<% end %>

<table>
  <thead>
    <tr>
      <th>Vehicle</th>
      <th>Date</th>
      <th>Desc</th>
      <th>Mileage</th>
      <th>Category</th>
      <th>Cost</th>
    </tr>
  </thead>

  <tbody>
    <% @vehicles.each do |vehicle| %>
      <tr>
        <td><%= vehicle.vehicle %></td>
        <td><%= vehicle.date %></td>
        <td><%= vehicle.desc %></td>
        <td><%= vehicle.mileage %></td>
        <td><%= vehicle.category %></td>
        <td><%= vehicle.cost %></td>
        <td><%= link_to 'Show', vehicle %></td>
        <td><%= link_to 'Edit', edit_vehicle_path(vehicle) %></td>
        <td><%= link_to 'Destroy', vehicle, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Vehicle', new_vehicle_path %><br/>
<%= link_to 'All Vehicles', vehicles_path %>

<h2>Import Vehicle Records</h2>

<%= form_tag import_vehicles_path, multipart: true do %>
   <%= file_field_tag :file %>
   <%= submit_tag "Import" %>
<% end %>

app/views/vehicles/new.html.erb
<h1>New vehicle</h1>

<%= render 'form' %>

<%= link_to 'Back', vehicles_path %>

app/views/vehicles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Vehicle:</strong>
  <%= @vehicle.vehicle %>
</p>

<p>
  <strong>Date:</strong>
  <%= @vehicle.date %>
</p>

<p>
  <strong>Desc:</strong>
  <%= @vehicle.desc %>
</p>

<p>
  <strong>Mileage:</strong>
  <%= @vehicle.mileage %>
</p>

<p>
  <strong>Category:</strong>
  <%= @vehicle.category %>
</p>

<p>
  <strong>Cost:</strong>
  <%= @vehicle.cost %>
</p>

<%= link_to 'Edit', edit_vehicle_path(@vehicle) %> |
<%= link_to 'Back', vehicles_path %>